services:
  # SERVICE 1: The PostgreSQL Database
  db:
    image: postgres:18.0
    container_name: ledger_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ledger
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d ledger" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # SERVICE 1.5: The Migrator
  migrate:
    image: migrate/migrate:v4.17.1
    container_name: ledger_migrator
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db/migration:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://admin:secret@db:5432/ledger?sslmode=disable", "up" ]

  # SERVICE 2: The Go API
  api:
    container_name: ledger_api
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      - DB_SOURCE=postgres://admin:secret@db:5432/ledger?sslmode=disable

  # SERVICE 3: Prometheus
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    depends_on:
      - api

  # SERVICE 4: Grafana
  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - prometheus

volumes:
  postgres_data:
